name: 'GitHub Action HelloWorld'
description: 'Custom GH Action TS'
author: 'Ali Qaryan'
inputs:
  name:
    description: 'Name to greet'
    required: true
    default: 'JS Marathon viewers'
runs:
  using: 'node16'
  main: 'dist/index.js'
